version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:5000"
    environment:
      - MONGO_URI=${AUTH_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  post-service:
    build: ./post-service
    ports:
      - "${POST_SERVICE_PORT}:5001"
    environment:
      - MONGO_URI=${POST_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  user-service:
    build: ./user-service
    ports:
      - "${USER_SERVICE_PORT}:5002"
    environment:
      - MONGO_URI=${USER_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
